version: '3.8'

services:

  canchu:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: canchu_container
    # volumes:
    #   - /home/ubuntu/EC2/Canchu/api1.0/public/:/public
    networks:
      - canchu_network

  redis:
    image: redis:6.0.16
    container_name: redis
    restart: always
    networks:
      - canchu_network

  nginx:
    image: nginx:1.18.0
    container_name: nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./private/certificate.crt:/etc/ssl/certificate.crt  # 替換為您的 SSL 證書路徑
      - ./private/private.key:/etc/ssl/private/private.key  # 替換為 SSL 私鑰的路徑
    networks:
      - canchu_network  
    depends_on:
      - canchu

networks:
  canchu_network:   
